@extends('includes.website.ajax_template')
@section('content')
<div class="user_prof">
    <div class="terms_wrapp">
        <div class="inner_wrapp">
            <div class="head_title">
                <h3>PRIVACY POLICY</h3>
            </div>
             <?php echo $privacyPolicy->Description ;  ?>
           <!--  <p>GoldenGirls is a private community built on trust. GoldenGirls take your privacy seriously. If you have any questions about this policy then you can contact us.
                This privacy policy sets out the basis on which any personal data that we have collected about you, or that you provide to us, will be processed by us. Please read the following carefully to understand our views and practices regarding your personal data and how we will treat it.
            </p>
            <p>We review this privacy policy regularly. Occasionally we may need to make changes or additions to this privacy policy that may affect how we handle your data. We will post new versions of this privacy policy on our website (the “Site”). We may also notify you of changes to this privacy policy by email. This privacy policy was last reviewed and updated.
            </p>
            <h4>INFORMATION WE HAVE COLLECTED AND MAY COLLECT AND HOW</h4>
            <p>When you register on our Site, we will collect some personal information from you, such as your name, email address, country of origin, location, occupation, photos, social media accounts and other data you upload or enter into your profile. This personal data is entered by you during the application or registration process or shared by you through another social media service, in order to become a member of GoldenGirls , apply for membership or other use of the GoldenGirls Service. We may also collect data about your navigation of the Site on an aggregate basis, such as your Internet Protocol Address (“IP Address”), which is identified and logged automatically in our server log files whenever you navigate the Site, your Internet Service Provider (“ISP”), your login frequency, the pages you visited within the Site, and the Internet browser or device you are using.
            </p>
            <p>When you participate in the Site member offers, complete forms for optional promotions, Site events, or participate in contests, surveys, or beta testing, we may require that you submit certain personal information to the Site, our mobile application or via email. You may also voluntarily provide personal information when you send us an enquiry or support request via email. When you contact us, we keep a record of your communication, and may use third party service providers (e-mail system provider, CRM systems), to help solve any issues you might be facing in the future. When you use GoldenGirls , you may share your location data for us to optimise your experience and inform you about other members nearby. You may also share your information on GoldenGirls , as well as interests, data that is shared with us and other members and may be used to suggest other members to connect to you and you to connect to other members.
            </p>
            <p>Surveys are periodically conducted to collect information to help us improve the Site. All information collected through surveys will remain confidential, even if we use a third party to help us conduct the survey, unless otherwise indicated.
            </p>
            <p>Any information you disclose in public areas of the Site may become public information. Please exercise caution when disclosing personal information in these areas. We are not responsible for any use by third parties of personal information disclosed by you in public areas of the Site.
            </p>
            <p>In order to facilitate the fulfilment of privileges for Members, You may authorise GoldenGirls to provide private data relevant to privilege redemption to privilege partners in question. Your approval will be requested before such data is exchanged. Any such exchange only happens for the fulfilment of privileges.</p>
            <h4>COOKIES</h4>
            <p>We use cookies on the Site and other technologies to recognise you and uniquely identify your browser. This helps us to provide you with a good user experience when you use the Site and also allows us to improve the Site. By continuing to use the Site, you are agreeing to our use of cookies.</p>
            <p>A cookie is a small file of letters and numbers that we store on your browser or the hard drive of your computer if you agree. Cookies contain information that is transferred to your computer's hard drive.</p>
            <p><b>We use the following cookies:</b></p>
            <p>Strictly necessary cookies. These are cookies that are required for the operation of the Site. They include, for example, cookies that enable you to log into secure areas of the Site.</p>
            <p>Analytical/performance/statistical cookies. They allow us to recognise and count the number of visitors and to see how visitors move around the Site when they are using it. This helps us to GoldenGirls improve the way the Site works, for example, by ensuring that users are finding what they are looking for easily.</p>
            <p>Functionality cookies. These are used to recognise you when you return to the Site. This enables us to personalise our content for you, greet you by name and remember your preferences (for example, your choice city).</p>
            <p>Targeting cookies. These cookies may record your visit to the Site and the pages you have visited on our Site. We will use this information to make the Site more relevant to your interests. We may use cookies to show you relevant content off the GoldenGirls site (e.g. for upcoming events from GoldenGirls on another social media channel). We may also use a cookie to learn whether someone took an action on our Site after displaying that content (e.g. booked a ticket).</p>
            <p>Please note that third parties (including, for example, providers of external services like web traffic analysis services) may also use cookies, over which we have no control. These cookies are likely to be analytical/performance cookies or targeting cookies.</p>
            <p>Most browsers are initially set up to accept cookies, but you can reset your browser to refuse all cookies or indicate when a cookie is being sent. You block cookies by activating the setting on your browser that allows you to refuse the setting of all or some cookies. However, if you use your browser settings to block all cookies (including essential cookies) you may not be able to access all or parts of the Site and your user experience may be inferior when navigating our Site.</p>

            <h4>WHY WE COLLECT INFORMATION</h4>
            <p>Information collected may be used to provide and improve our products and service of the Site; for billing, identification and authentication purposes; to analyse the Site usage for statistical purposes; to manage and improve our products and the Site; to deliver administrative and informative notices and communications relevant to your use of our products and the Site; for internal market research; for troubleshooting problems; for detecting, protecting against and preventing fraudulent or other criminal activity; for distribution to third party contractors who provide services to us (such as our email server) who are bound by our privacy restrictions or restrictions at least as restrictive as those set forth in this policy; to enforce our Terms of Service.</p>
            <h4>WITH WHOM WE SHARE</h4>
            <p>We may disclose your personal information to any member of our group, which means our subsidiaries, our ultimate holding company and its subsidiaries for outsourcing purposes (i.e. where such member of our group provides services for and on our behalf).</p>
            <p>When you submit information to GoldenGirls , it is collected, processed and maintained solely by us or by our third party contractors, those third party contractors being bound by our privacy policy or by restrictions at least as restrictive as those set forth in this policy.</p>
            <p>Partners may sponsor special member offers, promotions, privileges or contests that require you to disclose personal information to benefit from them. We will never disclose private member data, including email addresses, to partners without your prior express consent. Certain partners may require members to opt-in or agree to terms on the partners’ landing pages authorising us to provide member information to the partner in question. We advise you always to check our partners’ privacy policies before submitting information about yourself.</p>
            <p><b>We may disclose your personal information:</b></p>
            <p>in the event that we sell or buy any business or assets, in which case we may disclose your personal information to the prospective seller or buyer of such business or assets;
                to identify, contact or bring legal action against you if you are violating our Terms of Service or other rules or if we believe you are causing injury or interference with the rights of members, the general public or GoldenGirls .</p>
            <p>if we or substantially all of our assets are acquired by a third party, in which case personal information held by us will be some of the transferred assets; and
                if we are under a duty to disclose or share your personal information in order to comply with any legal obligation, or in order to enforce or apply our Terms of Service and other agreements or to protect our rights, property, or safety of our customers, or others.</p>
            <h4>OPTING IN OR OUT OF COMMUNICATIONS</h4>
            <p>By using the Site you are consenting to the terms of this privacy policy and you agree that GoldenGirls and its partners (if you have provided the respective partner your email address or have consented to us giving your email address to the respective partner) may send you communications regarding goods, services, events and other information that may be of interest to you. You may opt out of receiving communications from us and/or our partners, and from participating in member surveys at any time by either following the simple unsubscribe process set out in each email, sending us an email at or going to your account settings and deselecting the relevant boxes. Please be aware that on certain, rare occasions, we will send emails to communicate important corporate or member messages, like changes in our privacy policy or a receipt of your membership payment. These emails will not have an unsubscribe feature, as they are one-time only communications.</p>
            <p>If you supply us with your postal address, you may receive mailings from us with information on new products and services or upcoming events.</p>
            <p>To ensure removal from any lists, please provide us with your exact name, as it appears in your GoldenGirls profile, and address when communicating with us.</p> -->
        </div>
    </div>
</div>

@stop