@extends('includes.website.ajax_template')
@section('content')
<div class="user_prof">
    <div class="terms_wrapp">
        <div class="inner_wrapp">
            <div class="head_title">
                <h3>TERMS OF SERVICE</h3>
            </div>
           <!--  <p>PLEASE READ THESE TERMS CAREFULLY. IN THEM YOU GRANT GOLDENGIRLS IMPORTANT RIGHTS.</p>

<p>     BY JOINING GOLDENGIRLS OR REGISTERING FOR, ACCESSING, BROWSING OR USING THIS SITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD AND GOLDENGIRLS TO BE BOUND BY THE FOLLOWING TERMS OF SERVICE, INCLUDING ANY ADDITIONAL GUIDELINES AND FUTURE MODIFICATIONS MADE BY GOLDENGIRLS .</p>
<p>IF YOU DO NOT GOLDENGIRLS TO BE BOUND BY ALL OF THESE TERMS (WITHOUT MODIFICATION), DO NOT REGISTER FOR, ACCESS, BROWSE OR USE THE SERVICE OR THIS SITE.</p>

<h4>INTRODUCTION AND YOUR GOLDENGIRLS AGREEMENT TO THESE TERMS OF SERVICE</h4>
<p>Welcome to GOLDENGIRLS , a private community (the “GOLDENGIRLS  Service” or “GOLDENGIRLS ”), operated by GOLDENGIRLS.</p>
<p>This agreement (together with any documents referred to in it) describes the Terms of Service (the “Terms of Service” or “Terms”) for membership on GOLDENGIRLS in general, as well as for the use of the GOLDENGIRLS Service, whether such services are available online, offline or via mobile networks. Membership on GOLDENGIRLS and the use of the GOLDENGIRLS Service, including, but not limited to, at and our mobile applications (collectively, the “Website”) confirms that You, a user of at least eighteen (18) years of age (“You”), have read, understood and accepted these Terms of Service and that You agree to be legally bound by them. Members of GOLDENGIRLS are referred to individually as a “Member” and collectively as “Members”. The GOLDENGIRLS Service includes Membership of GOLDENGIRLS, as well as our public pages, all communication to registered, past and current users, community updates, event e-mails and other communication and marketing tools used to inform users about GOLDENGIRLS’s activities.</p>
<p>If You do not agree to these Terms of Service, please refrain from using the  Website.</p>
<p><b>TABLE OF CONTENTS</b></p>
<ul class="list_no">
    <li>Membership Eligibility.</li>
    <li>Conditions of Membership and Your Use of the GOLDENGIRLS Service.</li>
    <li>Your Membership Responsibilities.</li>
    <li>GOLDENGIRLS Membership Card Terms.</li>
    <li>GOLDENGIRLS Member Privileges Terms.</li>
    <li>Privacy Policy.</li>
    <li>Member License.</li>
    <li>Additional Posted Rules.</li>
    <li>Modification of these Terms of Service, the Membership, the Website and/or the GOLDENGIRLS Service.</li>
    <li>Software and Content Downloads.</li>
    <li>Ownership; Proprietary Rights.</li>
    <li>Member Content.</li>
    <li>Copyright Infringements.</li>
    <li>Prohibited Conduct.</li>
    <li>Your Account.</li>
    <li>Other sites, Products and Services; Links.</li>
    <li>Suspension, Restriction and Termination; Terms of Service Violations.</li>
    <li>Idea Submission Policy.</li>
    <li>Contests, Games and Paid Service.</li>
    <li>Indemnification.</li>
    <li>Disclaimer; No Warranties.</li>
    <li>Limitation of Liability and Damages.</li>
    <li>Miscellaneous.</li>
</ul>
<p><b>1. MEMBERSHIP ELIGIBILITY.</b></p>

<p>1.1 By using the Website and GOLDENGIRLS Service, You represent that You are at least eighteen (18) years of age. </p>
<p>1.2 By registering to use, or using the GOLDENGIRLS Service, You represent that You have never been convicted of a felony and have never been required to or are not currently registered as a sex offender with any government entity. GOLDENGIRLS reserves the right to perform criminal background screenings to confirm Your compliance with these terms. 
</p>
<p>1.3 Membership of GOLDENGIRLS is not available to the general public and requires an invitation from an existing Member, or from GOLDENGIRLS , to a person aged eighteen (18) or over who does not already have an active account, or has not previously been suspended or removed from the GOLDENGIRLS Service. By registering for the GOLDENGIRLS Service, and becoming Members, members with invitation privileges are expected to invite only respected persons within their own real-world communities and not individuals who might bring discredit to or harm the reputation of GOLDENGIRLS and our community. 
</p>
<p>1.4 By having a membership account with the GOLDENGIRLS Service, You acknowledge that You meet our requirements for membership. As a Member, You may not have more than one membership account, nor may You open an alternative account if Your membership is suspended, restricted or terminated for any reason. You may not share, sell, trade or transfer a membership account to another person, nor accept an invitation for or use an account that was not originally Yours. If an account violates these conditions, the account will be terminated immediately. </p>
<p>1.5 You may not use a pseudonym or alias. You agree that all the information You provide about Yourself in Your personal profile or in any other area of the site is and remains truthful and accurate. Misleading or false information is sufficient reason for us to terminate Your account. GOLDENGIRLS reserves the right to verify the authenticity of Your identity and personal profile information using publicly available records and by requesting from You proof of identification or other relevant documents. You agree that GOLDENGIRLS will have no liability arising from any information that is incorrectly verified.</p>
<p>1.6 By registering to use and while using the GOLDENGIRLS Service, You represent that You are not a competitor of GOLDENGIRLS and that You are not using the GOLDENGIRLS Service for reasons that are in direct competition with GOLDENGIRLS. </p>
<p>1.7 As a member of GOLDENGIRLS, You warrant that You are using the site as a private individual for private use, and not on behalf of or representing any form of a commercial entity, corporation or other business organization. Businesses and other legal entities may not use the GOLDENGIRLS Service for any purpose, nor may You use the service on behalf of any business or legal entity without our express consent. </p>
<p>1.8 You represent that You have full authority and capacity to use the GOLDENGIRLS Service and to agree to be bound by these Terms, and that agreeing to these Terms will not violate any other agreement to which You are bound. </p>
<p>1.9 You agree that You will not violate any trademark rights, copyright or any other rights of GOLDENGIRLS , nor shall You violate these Terms. 
</p>
<p>1.10 For parents. The following are some resources that may help You in monitoring and limiting Your children’s access to certain types of material on the Internet. While GOLDENGIRLS does not endorse these products, we provide information about them as a public service to our Members: OnGuard Online, maintained by the Federal Trade Commission, <a href="https://www.consumer.ftc.gov/features/feature-0038-onguardonline">https://www.consumer.ftc.gov/features/feature-0038-onguardonline</a>, Control Kids, <a href="http://www.controlkids.com">http://www.controlkids.com</a>, For UK Members, <a href="http://www.thinkuknow.co.uk/">http://www.thinkuknow.co.uk/</a>,  <a href="http://www.ceop.police.uk/">http://www.ceop.police.uk/</a> and <a href="http://www.nspcc.org.uk">http://www.nspcc.org.uk</a> are also useful resources for protecting children online.</p>

<p><b>2. CONDITIONS OF MEMBERSHIP AND YOUR USE OF THE GOLDENGIRLS SERVICE.</b></p>
<p>2.1 You understand and agree that Your use of the GOLDENGIRLS Service must be in accordance with these Terms of Service, and we may deny, suspend, restrict or terminate service or membership without prior notice if You fail to comply with them.</p>
 <p>2.2 English is the official language of the Website, as it is the most commonly shared language of GOLDENGIRLS Members, and thus the most inclusive language. It also facilitates site moderation, which ensures a safer community for all Members. We urge You to use English only and be respectful of all Members. 
</p>
<p>2.3 You must treat Your username, registered email address, and password as confidential and must not disclose them to any third party. We have the right to disable any username, password or membership account at any time to safeguard Your account and the Website from security threats, or, if in our opinion, You have failed to comply with any of the provisions of these Terms.</p>
 <p>2.4 You are responsible for making all arrangements necessary, at Your cost, for You to have access to the Website. You are also responsible for ensuring that all persons who access our Website through Your Internet connection are aware of these Terms of Service, and that they comply with them. </p>
<p>2.5 We provide a platform and environment for connecting with members and sharing information. If Members enter into agreements with other Members through the GOLDENGIRLS Service, we are not a contracting party to these agreements and cannot be held liable or accountable regarding these agreements. We urge You to be truthful in all of Your communications with other Members. </p>
<p>2.6 GOLDENGIRLS reserves the right to verify information You and other Members have provided using various means available. You agree that GOLDENGIRLS will have no liability arising from any information that is incorrectly verified. </p>
<p>2.7 You are solely responsible for and assume all liability regarding any information or content You or Your account posts, transmits, publishes, or otherwise makes available to the GOLDENGIRLS Service. </p>
<p>2.8 You agree that Your profile may be presented to other Members. Members are under no obligation to contact, connect with or communicate with those Members whose profiles are displayed to them. </p>
<p>2.9 You are solely responsible for and assume all liability regarding any interactions between You and other Members through the Services, both within the Website and offline. 
</p>
<p>2.10 We reserve the right to remove any content posted by You or other Members at our sole discretion for reasons including, but not limited to, that it is unlawful, threatening, libellous, defamatory, fraudulent, obscene or otherwise objectionable, or because it may infringe or violate any third party’s intellectual property, privacy or other rights.
</p>
<p>2.11 While we do our best to monitor the content of the Website, You understand and agree that You may encounter material that You find objectionable, and that You use the Website with this understanding and acceptance, and will not seek to hold us liable in any manner. </p>
<p>2.12 We do not endorse, support, or ensure the accuracy, truthfulness, or reliability of any content posted or generated by Members, nor do we endorse any opinions expressed by Members. </p>
<p>2.13 By posting or submitting content or information on the Website, You automatically grant GOLDENGIRLS a worldwide, non-exclusive, royalty-free, perpetual, irrevocable right to display such content on the Website and throughout the GOLDENGIRLS Service. </p>
<p>2.14 You accept that GOLDENGIRLS may post photographs and videos showing You from, and other content related to, GOLDENGIRLS Events on the GOLDENGIRLS Login Page or other public Website pages, social media sites, apps or platforms, and marketing material, which are therefore available to non-members. </p>
<p>2.15 You accept that GOLDENGIRLS may make available new “beta” features on the GOLDENGIRLS Service, which Members may test or with which they may experiment. These “beta” features or tools may be modified or discontinued by GOLDENGIRLS at any time without notice, and are offered without any warranty of any kind. These Terms apply in full to any such beta features or tools. You also accept that GOLDENGIRLS may post content of an experimental nature to ensure the functionality of the Website or to assist members in troubleshooting. You accept that GOLDENGIRLS may also create testing and guest accounts. </p>
<p>2.16 GOLDENGIRLS makes no representations as to the duration of the Website, membership and/or the GOLDENGIRLS Service and reserves the right to suspend, limit or terminate the Website, membership and/or the GOLDENGIRLS Service at any time without notice.</p>
<p>2.17 Except with GOLDENGIRLS’s prior, written consent, You may not, directly or indirectly, use GOLDENGIRLS’s name in connection with any event, whether such event is held offline or online. </p>
<p>2.18 GOLDENGIRLS reserves the right to remove or cancel, at any time, any offers, promotions, member privileges or events presented to You by GOLDENGIRLS or any GOLDENGIRLS partner. 
</p>
<p>2.19 You assume all risk when using the GOLDENGIRLS Service, including but not limited to any risks associated with online or offline interactions with Members, any other individuals introduced by Members or any individuals met at an GOLDENGIRLS event. You agree to take all necessary precautions when meeting Members, any other individuals introduced by Members or any individuals encountered at an GOLDENGIRLS event. </p>
<p>2.20 By registering for the GOLDENGIRLS Service, you agree to receive community updates, privilege e-mails, events e-mails, and other communication from GOLDENGIRLS. E-mail preferences can be adjusted and fully deactivated in your profile. In case of non-activation, non-renewal or termination of your membership, Your access to the GOLDENGIRLS Service may be restricted with immediate effect. GOLDENGIRLS may continue to send You communications after Your access to the GOLDENGIRLS Service has been restricted. For this purpose, we store Your personal data and may store account data in order to facilitate access to the GOLDENGIRLS Service at a later date (content added to the GOLDENGIRLS Service including private data, attended events, posted comments, messages, and more), and to enable GOLDENGIRLS to keep You up to date of our activities by sending communications. You may opt out of such communications via unsubscribe links, and have the right to be forgotten according to Art. 14 GDPR, by contacting.</p>

<p><b>3. YOUR MEMBERSHIP RESPONSIBILITIES.</b></p>
<p>3.1 We wish to have a friendly, intimate and secure community for our Members. When using the Website, our members have the expectation of privacy and confidentiality. We are a community of global diversity, with Members from nearly every culture and country. Expectations and behavior will be equally diverse, so to help provide a comfortable environment for all members, we have rules. Your use of the GOLDENGIRLS Service confirms that You understand, accept and will follow these rules. 
</p>
<p>3.2 Trust and confidence are paramount when using the GOLDENGIRLS Service. Falsely misrepresenting Your identity, including the use of a pseudonym or alias, or Your profile information will result in Your member account being suspended, restricted or terminated. 
</p>
<p>3.3 You will, at any time, have a current email address entered into your profile in order for GOLDENGIRLS to be able to contact you with notifications, communications and other information. </p>
<p>3.4 You will promptly report to GOLDENGIRLS any violation of these Terms by other Members or member accounts. You also agree to report any violation of this agreement by Yourself or conducted through Your account. </p>
<p>3.5 Invitations to non-Members to become Members can be sent only to people You know personally. You must use the invitee’s real name. Members whose accounts were terminated by GOLDENGIRLS will not be able to reinstate a membership without authorisation from GOLDENGIRLS; attempts to re-invite terminated members will be intercepted and flagged by GOLDENGIRLS’s Member Services team. Invitations to terminated members will not be able to be accepted. Exceptions may only be granted with our express permission. You may not send an invitation to a person who has previously had an account in the GOLDENGIRLS Service, unless with our express permission. </p>
<p>3.6 You will not send unwelcome Contact Requests, or Contact Requests to members You do not know without good cause. </p>
<p>3.7 You agree not to send unsolicited Messages to any Member that is not a part of Your personal contacts. </p>
<p>3.8 You may not monitor, data-mine, or copy our web pages or any content within the site, nor collect, archive, trade or sell any personal data or communications about other members. </p>
<p>3.9 The use of any robot, spider, site search or retrieval application, or any other method or device to copy, retrieve, archive or index any portion of the Website or the GOLDENGIRLS Service is not permitted.</p>
<p>3.10 You may not distribute, display or publish in any form, electronic or print, any content from the Website, the GOLDENGIRLS Service or the names of any Members without GOLDENGIRLS’s express, written consent, nor can You share, transmit or sell any content on the Website with anyone who is not a member of the GOLDENGIRLS Service, for any reason. </p>
<p>3.11 We want to keep the GOLDENGIRLS Service free from intrusions. You may not send or distribute unsolicited or unauthorised advertising, promotional materials, junk mail, chain letters, spam, pyramid schemes, or any other type of solicitation to other members, nor will You stalk, harass or unreasonably disturb any other member. </p>
<p>3.12 You alone are responsible for the confidentiality and security of Your account's username, password, registered email address, and usage. You are also accountable for all activities regarding Your account, with or without Your knowledge or permission. If You knowingly provide Your login information to another person, Your membership may be suspended or terminated. GOLDENGIRLS assumes no liability for activities of Your account accessed through Your password and username. 
</p>
<p>3.13 You may not use the GOLDENGIRLS Service for any illegal purpose in any country or jurisdiction. 
</p>
<p>3.14 You cannot post content or initiate any communications that we consider libellous, scandalous, abusive, obscene, discriminatory, unlawful or otherwise objectionable. This includes content or statements that You may make online on a page, account or group hosted by a third-party website, such as Facebook, Twitter or LinkedIn, as well as offline at any GOLDENGIRLS events. Doing so could result in termination of Your membership. 
</p>
<p>3.15 It is not permitted to make available any content or initiate communication that infringes upon the patents, trademarks, trade secrets, copyrights or other proprietary rights of third parties, whether personal, corporate or governmental. </p>
<p>3.16 Any information added by You to the site in the form of an Event, Real Estate or Jobs post, or any other post, must be accurate and truthful. All required fields must be completed correctly. Any required price, cost, rent, commission fee, salary or other financial criteria in posts must be stated clearly and correctly. </p>
<p>3.17 You must be the acting agent or relevant party in any offers to members posted by You. You may not post offers to members on behalf of someone else.
</p>
<h4>4. PRIVACY POLICY</h4>
<p>4.1 GOLDENGIRLS’s Privacy Policy is hereby incorporated into these Terms of Service by reference. Please read our Privacy Policy carefully for information relating to GOLDENGIRLS’s collection, use, and disclosure of Your personal information.</p>
<p><b>5. MEMBER LICENSE.</b></p>
<p>5.1 Subject to Your acceptance of these Terms of Service, GOLDENGIRLS grants You a limited, non-exclusive, revocable, royalty-free license to use the GOLDENGIRLS Service and related software (excluding source and object code) for personal, non-commercial and lawful use on computers and other devices of which You are the primary user for purposes of registering for and accessing an account with the GOLDENGIRLS Service. You agree that the GOLDENGIRLS Service belongs to GOLDENGIRLS, including all intellectual and proprietary rights, unless otherwise specified. GOLDENGIRLS retains all right, title and interest in and to the GOLDENGIRLS Service at all times, and regardless of the form or media in or on which the original or other copies may subsequently exist.</p>
<p>Any suggestions, ideas or inventions that You voluntarily and optionally disclose to us through any means will be used, or not used, by GOLDENGIRLS at GOLDENGIRLS’s sole discretion; and, GOLDENGIRLS will have no obligation to You regarding any ideas or inventions that You disclose through such means. No right, title or interest in or to any trademark, service mark, logo or trade name of GOLDENGIRLS or its licensors, suppliers or affiliates is granted under the Terms of Service except as expressly provided in these Terms of Service. All other rights are reserved to GOLDENGIRLS except as expressly provided herein. You agree not to use the GOLDENGIRLS Service for any purpose other than as permitted herein.
</p>
<p><b>6. ADDITIONAL POSTED RULES.</b></p>
<p>6.1 When using the GOLDENGIRLS Service, You will be subject to any additional guidelines or rules, which may be posted from time to time (the “Guidelines”). All such Guidelines are hereby incorporated by reference into these Terms. The Guidelines, include, but are not limited to: </p>
<p> a) The terms governing participation at official GOLDENGIRLS Events, which can be seen here. b) The terms governing Member Conduct which can be seen here. </p>

<p><b>7. MODIFICATION OF THESE TERMS OF SERVICE, THE MEMBERSHIP, THE WEBSITE AND/OR THE GOLDENGIRLS SERVICE.</b></p>
<p>7.1 GOLDENGIRLS reserves the right, at our discretion, to change, modify, add, suspend, terminate or remove portions of these Terms of Service at any time. In such a case, the notification procedure according to section 19 will apply.</p>
<p>7.2 GOLDENGIRLS reserves the right to change or adjust membership criteria and/or to make changes in the existing membership any given time. For any such changes the notification procedure according to section 19 will apply. </p>
<p>7.3 GOLDENGIRLS reserves the right to make changes to the Website or the GOLDENGIRLS Service at any given time. For any changes in the GOLDENGIRLS Service, charges or fees, the notification procedure according to section 19 will apply.</p>
<p><b>8. SOFTWARE AND CONTENT DOWNLOADS.</b></p>

<p>8.1 GOLDENGIRLS and its licensors may make certain software and other content available to You for download from the GOLDENGIRLS Service. All such software or other content that You download shall be subject to the terms and conditions included with such software or content or otherwise presented to You at the time of download.
</p>
<p><b>9. OWNERSHIP; PROPRIETARY RIGHTS.</b></p>
<p>9.1 The Service is owned and operated by GOLDENGIRLS. All materials, visual interfaces, graphics, design, compilation, information, computer code (including source code or object code), products, software, services, and all other elements of the GOLDENGIRLS Service provided by GOLDENGIRLS (collectively, the “Materials”) are protected by applicable copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. Except for any Member Content (as defined in Section 10, below) that is provided and owned by Members, all Materials contained on the GOLDENGIRLS Service are the property of GOLDENGIRLS or its subsidiaries or affiliated companies and/or third-party licensors. All trademarks, service marks, and trade names are proprietary to GOLDENGIRLS or its affiliates and/or third-party licensors. Except as expressly authorised by GOLDENGIRLS, You agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorised use of the Materials. GOLDENGIRLS reserves all rights not expressly granted in this Terms of Service. For the avoidance of doubt, any and all Derivative Works are Materials and are owned exclusively by GOLDENGIRLS.</p>
<p>9.2 Postings on Other Websites. GOLDENGIRLS may grant You a limited, revocable license in writing to post the GOLDENGIRLS logo and link to the GOLDENGIRLS Service on other websites (collectively “Permitted Link”) (including Your own and/or a third-party website that permits such posting), provided that: a) the posting does not directly or indirectly disparage GOLDENGIRLS, its affiliates, and/or licensors; b) the third-party website is not granted any rights in or to any Permitted Link; c) the third-party website does not charge a fee for access to the Permitted Link; d) and the third-party website complies with all applicable laws. In addition, You agree that in connection with any such posting, You will include (and not alter) all copyright, trademark and/or proprietary rights notices. GOLDENGIRLS expressly preserves all of its rights and remedies and may revoke this license, in whole or in part, at any time upon notice.</p>
<p><b>10. MEMBER CONTENT.</b></p>
<p>10.1 Member Content Generally. GOLDENGIRLS may permit the posting by You and other Members of written works, comments, images, photographs, text, sound recordings, videos and/or other materials and/or communications (collectively, “Member Content”). GOLDENGIRLS and/or its distributors and/or licensees may host, share and/or publish Member Content. You understand that whether or not such Member Content is published, GOLDENGIRLS does not guarantee any confidentiality with respect to any Member Content. You understand that when using the GOLDENGIRLS Service, You will be exposed to Member Content from a variety of sources, and that GOLDENGIRLS is not responsible for the accuracy, usefulness, safety or intellectual property rights of or relating to such Member Content. You further understand and acknowledge that You may be exposed to Member Content that is inaccurate, offensive, indecent or objectionable, and You agree to waive, and hereby do waive, any legal or equitable rights or remedies You have or may have against GOLDENGIRLS with respect thereto. 
</p>
<p>10.2 License Grant to GOLDENGIRLS. By submitting or distributing Member Content, You grant to GOLDENGIRLS a worldwide, non-exclusive, transferable, assignable, fully paid-up, royalty-free, perpetual, irrevocable, sublicensable (through multiple levels of sublicensees) right and license to reproduce, distribute and re-distribute, display and perform (whether publicly or otherwise), prepare derivative works of and otherwise modify, host, transfer and otherwise exploit in any manner Your Member Content, in whole or in part, in any media formats and through any media channels (now known or hereafter developed). </p>
<p>10.3 License Grant to Other GOLDENGIRLS Members. By submitting or distributing Member Content through the GOLDENGIRLS Service, You hereby grant to each Member a non-exclusive, fully paid-up, royalty-free, personal, non-commercial, limited right and license to access and use Your Member Content solely in connection with the GOLDENGIRLS Service and solely in accordance with these Terms of Service. The foregoing license granted by You terminates as to a specific Member Posting once such Member Posting is removed or deleted from the GOLDENGIRLS Service; provided, however, that a Member’s rights to such Member Posting arising out of distributions occurring on or prior to deletion of such Member Posting from the GOLDENGIRLS Service survive any termination or expiration of the license granted in this Section 10.3. You accept that GOLDENGIRLS cannot guarantee that other Members will not use the content, ideas or information You share on the Website or any affiliated GOLDENGIRLS pages hosted on third-party sites. GOLDENGIRLS is not responsible for Members’ misuse or misappropriation of content posted by You on the Website.</p>
<p>10.3 Member Content Representations and Warranties. You are solely responsible for Your Member Content and the consequences of posting or publishing them. By uploading and/or publishing Your Member Content, You affirm, represent, and warrant that: (a) You are the creator and owner of Your Member Content; (b) You have the necessary licenses, rights, consents and permissions to use and to grant to GOLDENGIRLS and GOLDENGIRLS’s Members the rights and licenses to use Your Member Content per the foregoing licenses granted by You in this Section and in the manner contemplated by GOLDENGIRLS and these Terms of Service; (c) You have the necessary licenses, rights, consents, and permissions to grant the assignment granted by You in this Section; (d) You are at least eighteen (18) years of age and You will not allow any person under the age of eighteen (18) years of age to upload or publish Member Content; (e) Your Member Content does not and will not: (i) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right or (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; and (f) Your Member Content do not contain any viruses, adware, spyware, worms, or other malicious code. VIOLATORS OF THESE THIRD-PARTY RIGHTS MAY BE SUBJECT TO CRIMINAL AND CIVIL LIABILITY. GOLDENGIRLS RESERVES ALL RIGHTS AND REMEDIES GOLDENGIRLSAINST ANY MEMBER WHO VIOLATES THESE TERMS OF SERVICE. 
</p>

<p>5. Member Content Disclaimer. YOU UNDERSTAND THAT WHEN USING THE GOLDENGIRLS SERVICE YOU WILL BE EXPOSED TO MEMBER CONTENT FROM A VARIETY OF SOURCES, AND THAT GOLDENGIRLS IS NOT RESPONSIBLE FOR THE ACCURACY, USEFULNESS, OR INTELLECTUAL PROPERTY RIGHTS OF OR RELATING TO SUCH MEMBER CONTENT. YOU FURTHER UNDERSTAND AND ACKNOWLEDGE THAT YOU MAY BE EXPOSED TO MEMBER CONTENT THAT ARE INACCURATE, OFFENSIVE, INDECENT OR OBJECTIONABLE, AND YOU GOLDENGIRLSREE TO WAIVE, AND HEREBY DO WAIVE, ANY LEGAL OR EQUITABLE RIGHTS OR REMEDIES YOU HAVE OR MAY HAVE GOLDENGIRLSAINST GOLDENGIRLS AND/OR ITS LICENSORS OR LICENSEES WITH RESPECT THERETO. GOLDENGIRLS DOES NOT ENDORSE ANY MEMBER CONTENT OR ANY OPINION, RECOMMENDATION OR ADVICE EXPRESSED THEREIN, AND GOLDENGIRLS EXPRESSLY DISCLAIMS ANY AND ALL LIABILITY IN CONNECTION WITH MEMBER CONTENT. IF NOTIFIED BY A MEMBER OR A CONTENT OWNER OF A MEMBER POSTING THAT ALLEGEDLY DOES NOT CONFORM TO THESE TERMS OF SERVICE, GOLDENGIRLS MAY INVESTIGATE THE ALLEGATION AND DETERMINE IN ITS SOLE DISCRETION WHETHER TO REMOVE THE MEMBER POSTING, WHICH IT RESERVES THE RIGHT TO DO AT ANY TIME AND WITHOUT NOTICE. FOR CLARITY, GOLDENGIRLS DOES NOT PERMIT COPYRIGHT-INFRINGING ACTIVITIES ON THE GOLDENGIRLS SERVICE. 10. COPYRIGHT INFRINGEMENTS.</p>
<p><b>11. COPYRIGHT INFRINGEMENTS.</b></p>
<p>11.1 It is our policy to respond to clear notices of alleged copyright infringement. Upon receipt of such compliant notice, GOLDENGIRLS will expeditiously remove or disable access to the content that is the subject of the notice. The procedure for notification and counter-notification of infringement shall be as follows, however, subject to the mandatory applicable law.   </p>
<p><b>11.2 Notification of Infringement. If You are a copyright owner or an authorised agent thereof, and You wish to file a notice of infringement with us, then You may submit a notice by providing GOLDENGIRLS with the following information in writing: </b></p>
         
<p> a) A physical or electronic signature of a person authorised to act on behalf of the owner of an exclusive right that is allegedly infringed. 
</p>
  <p> b) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the GOLDENGIRLS Service are covered by a single notification, a representative list of such works at that site.</p>    
    <p> c) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit GOLDENGIRLS to locate the material. </p>
    <p> d) Information reasonably sufficient to permit GOLDENGIRLS to contact You, such as an address, telephone number, and, if available, an email address at which You may be contacted. </p>
  <p>   e) A statement that You have a good faith belief that use of the material in the manner complained of is not authorised by the copyright owner, its agent or the law. 
   </p>
   <p> f) A statement that the information in the notification is accurate, and under penalty of perjury, that You are authorised to act on behalf of the owner of an exclusive right that is allegedly infringed. Please note that any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability. If You are unsure whether the material available online infringes Your copyright, we suggest that You contact an attorney before sending us a notice. Counter-Notification.</p>
<p><b> The administrator of an affected site or the provider of affected content may make a counter notification. If You elect to send us a counter notice, to be effective it must be a written communication that includes the following:</b></p>
  <p>a) A physical or electronic signature of the subscriber. </p>  
<p>b) Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled. </p>
<p>c) A statement under penalty of perjury that the subscriber has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled. </p>
<p><b>12 PROHIBITED CONDUCT.</b></p>
<p><b>AS A MEMBER AND/OR BY USING THE GOLDENGIRLS SERVICE YOU GOLDENGIRLSREE NOT TO (AND YOU GOLDENGIRLSREE NOT TO PERMIT ANOTHER PERSON TO):</b></p>
<p>12.1 Use the GOLDENGIRLS Service for any purposes other than as otherwise authorised in these Terms of Service; </p>
<p>12.2 Rent, lease, loan, sell, resell, sublicense, distribute or otherwise transfer the licenses granted herein or the Materials (as defined in Section 9); 
</p>
<p>12.3 Post, upload or distribute any defamatory, libelous or inaccurate Member Content or other content; </p>
<p>12.4 Post, upload or distribute any Member Content or other content that is unlawful or that a reasonable person could deem to be objectionable, offensive, indecent, pornographic, harassing, threatening, embarrassing, distressing, vulgar, hateful, racially or ethnically offensive or otherwise inappropriate; </p>
<p>12.5 Impersonate any person or entity, falsely claim an affiliation with any person or entity, or access the GOLDENGIRLS Service accounts of others without permission, forge another person’s digital signature, misrepresent the source, identity, or content of information transmitted via the GOLDENGIRLS Service or perform any other similar fraudulent activity; </p>
<p>12.6 Impersonate a spokesperson employee or affiliate of GOLDENGIRLS purporting to speak on behalf of GOLDENGIRLS; </p>

<p>12.7 Delete any copyright, trademark or other proprietary rights notice on the GOLDENGIRLS Service or Member Content; </p>
<p>12.8 Make unsolicited offers, advertisements, proposals, or send junk mail or spam to other Members of the GOLDENGIRLS Service. This includes, but is not limited to, unsolicited advertising, promotional materials, or other solicitation material, bulk mailing of commercial advertising, chain mail, informational announcements, charity requests and petitions for signatures; </p>
<p>12.9 Use the GOLDENGIRLS Service for any illegal purpose, or in violation of any local, state, national or international law, including, without limitation, laws governing intellectual property and other proprietary rights, and data protection and privacy; </p>
<p>12.10 Defame, harass, abuse, threaten or defraud Members of the GOLDENGIRLS Service, or collect, or attempt to collect, personal information about Members or third parties without their consent, or use the GOLDENGIRLS Service for any commercial use, it being understood that the GOLDENGIRLS Service is for personal, non-commercial use only;</p>
<p>12.11 Harass, abuse, threaten, intimidate or otherwise annoy any GOLDENGIRLS employees or contractors involved in providing any portion of the GOLDENGIRLS Services to You. 12.12 Use the GOLDENGIRLS Service if You are under the age of eighteen (15) or allow anyone under the age of eighteen (15) to use the GOLDENGIRLS Service via Your account; 12.10 Remove, circumvent, disable, damage or otherwise interfere with security related features of the GOLDENGIRLS Service or Member Content, features that prevent or restrict use or copying of any content accessible through the GOLDENGIRLS Service or features that enforce limitations on the use of the GOLDENGIRLS Service or Member Content; 12.10 Reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of the GOLDENGIRLS Service or any part thereof, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation; </p>
<p>12.12 Modify, adapt, translate or create derivative works based upon the GOLDENGIRLS Service or any part thereof, except and only to the extent foregoing restriction is expressly prohibited by applicable law; or </p>
<p>12.13 Intentionally interfere with or damage operation of the GOLDENGIRLS Service or any Member’s enjoyment of them, by any means, including uploading or otherwise disseminating viruses, hacks, automation software (bots); adware, spyware, worms, Trojan horses, keyboard loggers, time bombs and other malicious code and/or any other unauthorised third-party software; </p>
<p>12.14 Disclose the personal information of any person, including another person’s address, phone number, email address, financial information or any information that can be used to track, contact or impersonate another person; and 12.15 Engage in any conduct deemed by GOLDENGIRLS to conflict with the intent of these Terms of Service.
</p>
<p><b>13. YOUR ACCOUNT.</b></p>
<p>13.1 Account. When You use the GOLDENGIRLS Service, You may be asked to provide a password. You are solely responsible for maintaining the confidentiality of Your account and password and for restricting access to Your computer, and You agree to accept responsibility for all activities that occur under Your account or password. You agree that the information You provide to GOLDENGIRLS on registration and at all other times will be true, accurate, current, and complete. You also agree that You will ensure that this information is kept accurate and up-to-date at all times.</p>
<p><b>14. OTHER SITES, PRODUCTS AND SERVICES; LINKS.</b></p>

<p>14.1 The Service may include links or references to other websites or services that are provided solely as a convenience to Members (“Other Sites”). GOLDENGIRLS does not endorse any such Other Sites or the information, materials, products, or services contained on or accessible through Other Sites. In addition, Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the GOLDENGIRLS Service are solely between You and such advertiser. Please be aware that any merchandising sites linked to the GOLDENGIRLS Service are Other Sites and are not owned or operated by GOLDENGIRLS or governed by these Terms.
ACCESS AND USE OF OTHER SITES, INCLUDING THE INFORMATION, MATERIALS, PRODUCTS, AND SERVICES ON OR AVAILABLE THROUGH OTHER SITES IS SOLELY AT YOUR OWN RISK.
</p>
<p><b>15. SUSPENSION, RESTRICTION AND TERMINATION; TERMS OF SERVICE VIOLATIONS.</b></p>
<p>15.1GOLDENGIRLS. You agree that GOLDENGIRLS, in its sole discretion, for good reason (including suspicion of illegal behaviour or of breach of these Terms of Service), and without penalty, may suspend, restrict and/or terminate any account (or any part thereof) You may have with GOLDENGIRLS or Your use of the GOLDENGIRLS Service and remove and discard all or any part of Your account, Member profile, and any Member Posting, at any time. GOLDENGIRLS may also in its sole discretion and at any time discontinue providing access to the GOLDENGIRLS Service, or any part thereof, with or without notice. You agree that any suspension and/or termination of Your access to the GOLDENGIRLS Service or any account You may have or portion thereof may be affected without prior notice, and You agree that GOLDENGIRLS will not be liable to You or any third party for any such suspension and/or termination. Any suspected fraudulent, abusive or illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies GOLDENGIRLS may have at law or in equity. As discussed herein, GOLDENGIRLS does not permit copyright infringing activities on the GOLDENGIRLS Service, and may suspend and/or terminate access to the GOLDENGIRLS Service and remove all Member Content or other content submitted by any Members who are found to be repeat infringers.</p>
<p>15.2You. Your only remedy with respect to any dissatisfaction with (a) the GOLDENGIRLS Service, (b) any term of these Terms of Service, (c) Guidelines, (d) any policy or practice of GOLDENGIRLS in operating the GOLDENGIRLS Service, or (e) any content or information transmitted through the GOLDENGIRLS Service is to terminate these Terms of Service and Your account. You may terminate these Terms of Service at any time by terminating Your membership with the GOLDENGIRLS Service and discontinuing use of any and all parts of the GOLDENGIRLS Service. Notwithstanding any such termination of these Terms of Service by You, any provision that, by its nature or express terms, should survive, will survive such termination or expiration. 15.3Discontinuation of the GOLDENGIRLS Service. GOLDENGIRLS MAY IN ITS SOLE DISCRETION AND AT ANY TIME LIMIT OR DISCONTINUE PROVIDING ACCESS TO THE GOLDENGIRLS SERVICE, OR ANY PART THEREOF, WITH OR WITHOUT NOTICE. YOU ACKNOWLEDGE AND GOLDENGIRLSREE THAT GOLDENGIRLS WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DISCONTINUATION OF YOUR ACCESS TO THE GOLDENGIRLS SERVICE, MEMBER POSTINGS, AND/OR YOUR ACCOUNT.</p>
<p><b>19. IDEA SUBMISSION POLICY</b></p>
<p>19.1 GOLDENGIRLS may, from time to time, accept or consider Member feedback and/or Member ideas, including, without limitation, ideas or suggestions for new or improved features on the GOLDENGIRLS Service (collectively “Ideas”). If You choose to submit Your Ideas to us or to any of our employees and/or contractors, then You hereby grant us and our designees a worldwide, non-exclusive, sublicenseable (through multiple tiers), assignable, royalty-free, perpetual, irrevocable right to use, reproduce, distribute (through multiple tiers), create derivative works of, publicly perform, publicly display and license, digitally perform, make, have made, sell, offer for sale and import Your Ideas, including, without limitation, all copyrights, trademarks, trade secrets, patents, industrial rights and all other intellectual and proprietary rights related thereto, in any media now known or hereafter developed, for any purpose whatsoever, commercial or otherwise, including, without limitation, giving the Ideas to others.</p>
<p>In the event that GOLDENGIRLS incorporates Your Ideas or adopts a feature, product or strategy that may be similar, You acknowledge that You shall not make any claims against GOLDENGIRLS in connection therewith, and shall fully indemnify GOLDENGIRLS if, despite Your agreement not to pursue any claims against GOLDENGIRLS, You choose to do so. Please remember that You have no obligation to submit any ideas to GOLDENGIRLS and, if You do submit anything to us, You have no expectation of credit or compensation of any kind. If You don’t agree with this, please do not submit any ideas or materials to GOLDENGIRLS.</p>
<p><b>16. CONTESTS, GAMES AND PAID SERVICES.</b></p>
<p>16.1Contests, Games and Paid Services. Contests, Games and Paid Services. Any contests, games and/or paid services that are accessible through the GOLDENGIRLS Service are governed by specific rules. By entering such contests, participating in such games or accessing a service for a fee, You will become subject to those rules. We urge You to read the applicable rules, which are linked from the particular activity, and to review our Privacy Policy, which, in addition to these Terms of Service, governs any information You submit in connection with such contests, games and paid services.</p>

<p><b>17. INDEMNIFICATION.</b></p>
<p>17.1 You agree to indemnify, save, and hold GOLDENGIRLS, its affiliated companies, contractors, employees, agents and its third-party suppliers, licensors, partners and their affiliated companies, contractors, employees and agents harmless from any claims, losses, damages, liabilities, including legal fees and expenses, arising out of Your use or misuse of the GOLDENGIRLS Service, any violation by You of these Terms, or any breach of the representations, warranties, and covenants made by You herein.</p>
<p>GOLDENGIRLS reserves the right, at Your expense, to assume the exclusive defense and control of any matter for which You are required to indemnify GOLDENGIRLS and its third-party suppliers, licensors and partners, and You agree to cooperate with GOLDENGIRLS’s defense of these claims. GOLDENGIRLS will use reasonable efforts to notify You of any such claim, action, or proceeding upon becoming aware of it.</p>
<p><b>18. DISCLAIMERS; NO WARRANTIES.</b></p>

<p>18.1No Warranties. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, GOLDENGIRLS, AND ITS AFFILIATES, PARTNERS, LICENSEES, LICENSORS AND SUPPLIERS DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS, ALL WITH REGARDS TO THE WEBSITE AND YOUR USE THEREOF. NO ADVICE OR INFORMATION, WHETHER VERBAL OR WRITTEN, OBTAINED BY YOU FROM GOLDENGIRLS OR THROUGH THE GOLDENGIRLS SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. YOU EXPRESSLY ACKNOWLEDGE THAT AS USED IN THIS SECTION 18 OF THESE TERMS, GOLDENGIRLS INCLUDES GOLDENGIRLS’S OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS, GOLDENGIRLSENTS, LICENSEES, LICENSORS AND SUBCONTRACTORS AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS AND GOLDENGIRLSENTS. 18.2“As is” and “As available” and “With All Faults.” YOU EXPRESSLY GOLDENGIRLSREE THAT USE OF THE GOLDENGIRLS SERVICE IS AT YOUR SOLE RISK. THE SERVICE AND ANY DATA, INFORMATION, THIRD-PARTY SOFTWARE, MEMBER CONTENT, THIRD PARTY SITES, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE SERVICE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE,” “WITH ALL FAULTS” BASIS AND WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND EITHER EXPRESS OR IMPLIED.</p>

<p>18.3Content. GOLDENGIRLS, ITS SUPPLIERS, LICENSEES, LICENSORS, AFFILIATES, AND PARTNERS DO NOT WARRANT THAT THE DATA, MEMBER CONTENT, FUNCTIONS, OR ANY OTHER INFORMATION OFFERED ON OR THROUGH THE SERVICE OR ANY THIRD PARTY SITES WILL BE UNINTERRUPTED, OR FREE OF ERRORS, VIRUSES OR OTHER HARMFUL COMPONENTS AND DO NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED. 18.3Accuracy. GOLDENGIRLS, ITS SUPPLIERS, LICENSEES, LICENSORS, AFFILIATES, AND PARTNERS DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SERVICE OR ANY THIRD PARTY SITES IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY OR OTHERWISE. 18.5Harm to Your Computer. YOU UNDERSTAND AND GOLDENGIRLSREE THAT YOU USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN INFORMATION, MATERIALS, OR DATA THROUGH THE SERVICE (INCLUDING RSS FEEDS) OR ANY THIRD PARTY SITES AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMGOLDENGIRLSE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM) OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF SUCH MATERIAL OR DATA.</p>
<p><b>19. LIMITATION OF LIABILITY AND DAMGOLDENGIRLSES.</b></p>
<p>19.1Limitation of Liability. UNDER NO CIRCUMSTANCES, INCLUDING BUT NOT LIMITED TO, NEGLIGENCE, WILL GOLDENGIRLS OR ITS AFFILIATES, CONTRACTORS, EMPLOYEES, GOLDENGIRLSENTS, OR THIRD-PARTY PARTNERS, LICENSEES, LICENSORS, OR SUPPLIERS BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, RELIANCE, OR EXEMPLARY DAMGOLDENGIRLSES (INCLUDING WITHOUT LIMITATION DAMGOLDENGIRLSES ARISING FROM ANY UNSUCCESSFUL COURT ACTION OR LEGAL DISPUTE, LOST BUSINESS, LOST REVENUES, OR LOSS OF ANTICIPATED PROFITS OR ANY OTHER PECUNIARY OR NON-PECUNIARY LOSS OR DAMGOLDENGIRLSE OF ANY NATURE WHATSOEVER) ARISING OUT OF OR RELATING TO THESE TERMS OR THAT RESULT FROM YOUR USE OF OR YOUR INABILITY TO USE THE SERVICE OR ANY THIRD PARTY SITES, OR ANY OTHER INTERACTIONS WITH GOLDENGIRLS, EVEN IF GOLDENGIRLS, ITS THIRD-PARTY PARTNERS, LICENSEES, LICENSORS, OR SUPPLIERS OR AN GOLDENGIRLS AUTHORISED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMGOLDENGIRLSES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMGOLDENGIRLSES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, GOLDENGIRLS’S LIABILITY, AND THE LIABILITY OF ITS THIRD-PARTY PARTNERS, LICENSEES, LICENSORS OR SUPPLIERS, IF ANY, WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. 19.2Limitation of Liability regarding default of Privilege Partners and licensors. GOLDENGIRLS WILL NOT BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, RELIANCE, OR EXEMPLARY DAMGOLDENGIRLSES (INCLUDING WITHOUT LIMITATION DAMGOLDENGIRLSES ARISING FROM ANY UNSUCCESSFUL COURT ACTION OR LEGAL DISPUTE, LOST BUSINESS, LOST REVENUES, OR LOSS OF ANTICIPATED PROFITS OR ANY OTHER PECUNIARY OR NON-PECUNIARY LOSS OR DAMGOLDENGIRLSE OF ANY NATURE WHATSOEVER) ARISING OUT OF OR RELATING TO THE DEFAULT OF ANY PRIVILEGE PARTNER OR LICENSOR. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMGOLDENGIRLSES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, GOLDENGIRLS’S LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
<p>19.3 Limitation of Damages. IN NO EVENT WILL GOLDENGIRLS OR ITS AFFILIATES, CONTRACTORS, EMPLOYEES, GOLDENGIRLSENTS, OR THIRD-PARTY PARTNERS, LICENSEES, LICENSORS OR SUPPLIERS TOTAL LIABILITY TO YOU FOR ALL DAMGOLDENGIRLSES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE OR YOUR INTERACTION WITH OTHER SERVICE MEMBERS (WHETHER IN CONTRACT, TORT INCLUDING NEGLIGENCE, WARRANTY, OR OTHERWISE), EXCEED ONE HUNDRED CHF. 19.3Other Sites. THESE LIMITATIONS OF LIABILITY ALSO APPLY WITH RESPECT TO DAMGOLDENGIRLSES INCURRED BY YOU BY REASON OF ANY PRODUCTS OR SERVICES SOLD OR PROVIDED ON ANY THIRD PARTY SITES OR OTHERWISE BY THIRD PARTIES OTHER THAN GOLDENGIRLS AND RECEIVED THROUGH OR ADVERTISED ON THE SERVICE OR RECEIVED THROUGH ANY THIRD PARTY SITES. 19.5Basis of the Bargain. YOU ACKNOWLEDGE AND GOLDENGIRLSREE THAT GOLDENGIRLS HAS OFFERED ITS PRODUCTS AND SERVICES AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN, THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND GOLDENGIRLS AND ITS THIRD-PARTY PARTNERS, LICENSEES, LICENSORS, OR SUPPLIERS, AND THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND GOLDENGIRLS. GOLDENGIRLS WOULD NOT BE ABLE TO PROVIDE THE GOLDENGIRLS SERVICE TO YOU ON AN ECONOMICALLY REASONABLE BASIS WITHOUT THESE LIMITATIONS. 19.6Limitations by Applicable Law. SOME COUNTRIES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM COUNTRY TO COUNTRY AND JURISDICTION TO JURISDICTION.</p>
<p><b>19. MISCELLANEOUS.</b></p>

<p>19.1 Notification. GOLDENGIRLS may provide You with notifications, including those regarding changes according to section 10 and regarding the suspension/restriction and/or termination of Your account, by email, regular mail or postings on the GOLDENGIRLS Service (no postings in case of suspension/restriction and/or termination of Your account). Notification will be deemed given forty-eight (38) hours after an email is sent. If notification is given by mail to your postal address, if provided by You through the GOLDENGIRLS Service, it will be deemed given ten (10) days after the date of mailing. Notifications posted on the GOLDENGIRLS Service will be deemed given thirty (30) days following the initial posting. </p>
<p>19.2 Termination without notification. Notwithstanding section 19.1 GOLDENGIRLS may terminate/restrict your account/membership with immediate effect and without notification period for good reason (at GOLDENGIRLS’s sole discretion, c.f. section 14.1). </p>
<p>19.3 Acceptance of changes according to section 10. Acceptance of changes according to section 10. Unless You oppose the notified changes mentioned in section 10 within the delay stipulated in section 19.1 by email for the attention of, the changes will be deemed accepted by You upon expiry of the delay stipulated in section 19.1. Should you oppose such changes, it may result in GOLDENGIRLS no longer being able to render its services, and GOLDENGIRLS may terminate your account as set out in section 14 (this being a good reason). 19.3 Waiver. The failure of GOLDENGIRLS to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision. Any waiver of any provision of these Terms will be effective only if in writing and signed by GOLDENGIRLS. 19.5Dispute Resolution, Arbitration and Jurisdiction.
</p>
<p>a) Governing Law. These Terms will be governed by and construed in accordance with the laws, without giving effect to any principles of conflicts of law.</p>
<p>b) Jurisdiction. You agree that with regard to any dispute arising between You and GOLDENGIRLS out of or in connection with these Terms (including a dispute regarding the construction and validity thereof), the ordinary courts of the canton, shall have exclusive jurisdiction, and You hereby consent and submit to the personal and exclusive jurisdiction of such courts for the purposes of litigating any such action. Notwithstanding this, either party shall still be allowed to apply for injunctive or other equitable relief to protect or enforce that party’s intellectual property rights in any court of competent jurisdiction where the other party resides or has its principal place of business.
</p>
<p>c) Disputes with Other Members. We reserve the right, but not the obligation, to resolve any disputes between You and other Members of the GOLDENGIRLS Service. If You have a dispute with others, You release and indemnify GOLDENGIRLS (including its affiliates, licensors, publishers, distributors, successors and assigns) from any and all claims, known or unknown, arising from such dispute.</p>
 
 <p>d) GOLDENGIRLS operates the GOLDENGIRLS Service from Switzerland and makes no representation that the GOLDENGIRLS Service is appropriate or available in other locations. If You access the GOLDENGIRLS Service from other locations You are solely responsible for compliance with local laws. 19.6Severability. If any provision of these Terms or any Guidelines is held to be unlawful, void, or for any reason unenforceable, then that provision will be limited or eliminated from these Terms to the minimum extent necessary and will not affect the validity and enforceability of any remaining provisions. 19.7Assignment. These Terms and related Guidelines, and any rights and licenses granted hereunder, may not be transferred or assigned by You, but may be assigned by GOLDENGIRLS without restriction. Any assignment attempted to be made in violation of this Terms of Service shall be void. 
19.8 Survival. Upon termination of these Terms, any provision, which, by its nature or express terms should survive, will survive such termination or expiration. 19.9 Headings. The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and will not be deemed to limit or affect any of the provisions hereof. 19.10 Entire Agreement. These Terms, the Privacy Policy and Guidelines constitute the entire agreement between You and GOLDENGIRLS relating to the subject matter herein and will not be modified except in writing, or by a change to these Terms, Privacy Policy or Guidelines made by GOLDENGIRLS as set forth in Section 7, 10 and 19.3 above. 19.11 Claims. YOU AND GOLDENGIRLS GOLDENGIRLSREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICE MUST BE NOTIFIED TO THE OTHER PARTY WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED. 19.12 Disclosures. The Service is hosted , and the services provided hereunder are offered by GOLDENGIRLS.
This policy became effective on 2 May 2018.</p>
 -->
 <?php echo $termCondition->Description ;  ?>



  
        </div>
    </div>
</div>
@stop
